export const partners = [
  { src: "./public/partners/coca-cola.png", name: "Coca Cola HBC" },
  { src: "./public/partners/draft-kings.png", name: "DraftKings" },
  { src: "./public/partners/indeaver.png", name: "Indeavr" },
  { src: "./public/partners/post-bank.png", name: "PostBank" },
  { src: "./public/partners/smart-it.png", name: "SmartIt" },
  { src: "./public/partners/software-group.png", name: "Software Group" },
  { src: "./public/partners/super-hosting.png", name: "SuperHosting" },
  { src: "./public/partners/schwarzIT.png", name: "SchwarzIT" },
  { src: "./public/partners/pharVision.png", name: "PharVision" },
  { src: "./public/partners/pokerstars.png", name: "PokerStars" },
  { src: "./public/partners/dxc.png", name: "DXC" },
  { src: "./public/partners/createx.png", name: "CreateX" },
  { src: "./public/partners/ambitioned.png", name: "Ambitioned" },
  { src: "./public/partners/bosch.png", name: "Bosch Digital" },
];
