export const partners = [
    { src: "https://softuni.bg/Files/Companies/Partners/Platinum/Coca%20Cola%20HBC.jpg", name: "Coca Cola HBC Bulgaria" },
    { src: "https://softuni.bg/companies/profile/logo/2", name: "XS Software" },
    { src: "https://softuni.bg/companies/profile/logo/418", name: "Цюлке Инженеринг ЕООД" },
    { src: "https://softuni.bg/companies/profile/logo/33", name: "SmartIT" },
    { src: "https://softuni.bg/companies/profile/logo/269", name: "SBTech Bulgaria" },
    { src: "https://softuni.bg/companies/profile/logo/38", name: "Софтуер Груп БГ" },
    { src: "https://softuni.bg/companies/profile/logo/32", name: "СуперХостинг.БГ" },
    { src: "https://softuni.bg/companies/profile/logo/134", name: "Telenor Bulgaria" },
    { src: "https://softuni.bg/companies/profile/logo/123", name: "Indeavr" },
    { src: "https://softuni.bg/companies/profile/logo/41", name: "INFRAGISTICS" },
    { src: "https://softuni.bg/companies/profile/logo/345", name: "Пощенска Банка" },
    { src: "https://softuni.bg/companies/profile/logo/371", name: "Моушън Софтуер" },
    { src: "https://softuni.bg/companies/profile/logo/241", name: "Tek Experts" },
];
