export const partners =  [
    { src: "https://softuni.bg/Files/Companies/Partners/Platinum/Coca%20Cola%20HBC.jpg", name: "Coca Cola HBC Bulgaria" },
    { src: "https://softuni.bg/companies/profile/logo/2", name: "XS Software" },
    { src: "https://softuni.bg/companies/profile/logo/418", name: "Цюлке Инженеринг ЕООД" },
    { src: "https://softuni.bg/companies/profile/logo/33", name: "SmartIT" },
    { src: "https://softuni.bg/companies/profile/logo/269", name: "SBTech Bulgaria" },
    { src: "https://softuni.bg/companies/profile/logo/38", name: "Софтуер Груп БГ" },
    { src: "https://softuni.bg/companies/profile/logo/128", name: "ScaleFocus" },
    { src: "https://softuni.bg/companies/profile/logo/32", name: "СуперХостинг.БГ" },
    { src: "https://softuni.bg/companies/profile/logo/134", name: "Telenor Bulgaria" },
    { src: "https://softuni.bg/companies/profile/logo/123", name: "Indeavr" },
    { src: "https://softuni.bg/companies/profile/logo/41", name: "INFRAGISTICS" },
    { src: "https://softuni.bg/companies/profile/logo/345", name: "Пощенска Банка" },
    { src: "https://softuni.bg/companies/profile/logo/371", name: "Моушън Софтуер" },
    { src: "https://softuni.bg/companies/profile/logo/88", name: "Netpeak" },
    { src: "https://softuni.bg/companies/profile/logo/241", name: "Tek Experts" },
    { src: "https://softuni.bg/Files/Companies/Partners/Gold/logo%20stemo%20soft%20house%20PRIMARY_facebook.png", name: "Stemo" },
    { src: "https://softuni.bg/Files/Companies/Partners/Gold/REWE%20Digital%20100px%20Logo%20NEW%20(003).png", name: "Rewe Digital" },
    { src: "https://softuni.bg/Files/Companies/Partners/Gold/grand%20optics_facebook.jpg", name: "Grand & Joy Optics" },
    { src: "https://softuni.bg/companies/profile/logo/380", name: "bet365" },
    { src: "https://softuni.bg/companies/profile/logo/388", name: "Ever Technologies" },
    { src: "https://softuni.bg/companies/profile/logo/30", name: "Нет Инфо АД" },
    { src: "https://softuni.bg/companies/profile/logo/381", name: "АРДЕС Информационни Технологии ЕООД" },
    { src: "https://softuni.bg/companies/profile/logo/144", name: "ATIA & Tiger Technology" },
    { src: "https://softuni.bg/companies/profile/logo/287", name: "Негометрикс България ЕООД" }
];